Unit Test - Merkle
gnosis/dex-plasma pull request #10
Opened 2018-09-10 15:44 UTC by bh2smith

Four test cases giving nearly full coverage of Merkle.sol

2018-09-10 16:26 UTC, fleupold requested changes
I believe you don't want to use a Mock here, but instead expose `checkMembership` with the `height` parameter somehow in the test. I'm usually not a fan of subclassing things just for tests, as unit tests should really just test the public interface of a class and not implementation details.
Therefore, if we want to test the sub-function, I'd argue we should expose it publicly on the main contract. Currently it's made internal and I don't even see from where it is used.

How long does the computation of a single merkle proof take in the test? Would it be feasible to test all permutation of a let's say 4 element tree + a bad index and a bad hash? 

Could we also add tests for if `proof` is too long or too short or `index` is out of range?

2018-09-10 16:26 UTC, fleupold commented on contracts/mocks/MerkleMock.sol
> +contract MerkleMock {
Would we be able to use the mock-contract here? Right now it doesn't really seem to be a mock but instead do some actual computation.

2018-09-10 16:26 UTC, fleupold commented on test/merkle.js
> +      res = (await merkle.checkMembership(leaf, index, tree_root, proof, 3));
It looks like you are testing the Mock here. The class under test should really never be mocked. Mocks should be injected into the class under test instead of real life dependencies (e.g. a ERC20 token that is passed in the constructor).


Why do you need this extra object? Would it make sense to add that convenience function to the actual contract itself?

2018-09-10 16:26 UTC, fleupold commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
It would be awesome if you could somehow programatically derive this value. Tests can also serve as a great documentation on how the library is expected to be used. Right now I have no idea how you come up with this value.

2018-09-10 16:26 UTC, fleupold commented on test/merkle.js
> +    it('Height 3, leaf 0, proof 0', async () => {
What does proof 0 mean?

2018-09-10 16:26 UTC, fleupold commented on test/merkle.js
> +      assert.equal(res, false, "Not contained! Good proof, bad index");
nit: Maybe say "index doesn't match proof"?

2018-09-10 18:04 UTC, bh2smith commented on test/merkle.js
> +      res = (await merkle.checkMembership(leaf, index, tree_root, proof, 3));
This is apparently the standard for testing libraries (i.e. they need to be used by a contract). I gathered this knowledge  from the openzeppelin-solidity repo as this is how they test their librares.  [Here|https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/mocks/MathMock.sol] is an example of a contract using *Math.sol*. 

Considering that Merkle should be a utility contract and potentially moved into a standalone location, I also think that it should have its own unit tests. It is, after all, a standalone structure.

2018-09-10 18:05 UTC, bh2smith commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
Yes I agree completely. I constructed these examples in python, could you suggest a nice way to include these pieces into the project? Perhaps a "generator" directory inside test? Would this interfere with truffle's test suite?

2018-09-10 18:06 UTC, bh2smith commented on test/merkle.js
> +    it('Height 3, leaf 0, proof 0', async () => {
It means it is the proof for the leaf at index zero (i.e. correct proof). I will try to elaborate these better. Suggestions warmly welcome.

2018-09-10 18:10 UTC, bh2smith commented on contracts/mocks/MerkleMock.sol
> +contract MerkleMock {
It doesn't appear to be a mock with direct regards to [your|https://github.com/fleupold/mock-contract] your notion, but it does coincide with the unit tests for solidity libraries according to [openzeppelin|https://github.com/OpenZeppelin/openzeppelin-solidity/]. Are there any other suggested terms one might want to consider?

2018-09-10 18:13 UTC, bh2smith commented on test/merkle.js
> +      assert.equal(res, false, "Not contained! Good proof, bad index");
Yes, actually I should change this completely since this message is only meant to be displayed upon failure of passing the test case.

2018-09-11 08:21 UTC, fleupold commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
How about just generating them with js code right in the test?

2018-09-11 08:31 UTC, fleupold commented on test/merkle.js
> +      res = (await merkle.checkMembership(leaf, index, tree_root, proof, 3));
Ah I get it now. I missed that Merkle.sol is a library and not a contract. Sorry about the confusion.

I think the name Mock is very misleading and something that OpenZeppelin should consider revisiting (I'm happy to open an issue in their repo). A mock is something that should never be the system under test.
It's really just a `MerkleFacadeContract` or `MerkleWrapperContract` for the underlying library.

I'd also argue all it should do it call the library method directly and not have any additional if/else logic.

2018-09-11 08:32 UTC, fleupold commented on contracts/mocks/MerkleMock.sol
> +contract MerkleMock {
as per suggestion below. Maybe MerkleLibraryFacade or MerkleLibraryWrapper?

2018-09-11 08:47 UTC, bh2smith commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
Ya, I'm sure that could be done... might take me sometime to get it right.

2018-09-11 08:50 UTC, bh2smith commented on test/merkle.js
> +      res = (await merkle.checkMembership(leaf, index, tree_root, proof, 3));
I was trying to call the library methods directly, but got some dumb complaint about not specifying the right number of parameters for my method call. In order to work around this, I used the if statement to define only a single function that called both. 

Would you agree that we don't actually need those two duplicate methods in the Merkle Library? I would be very happy to take the one without the "height" parameter out. Its not like typing 16 every time is an inconvenience. Suggestions? 

I would be happy to land on an appropriate alternative such as "Facade" or "Wrapper".

2018-09-11 10:17 UTC, josojo commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
Let's try do to it. We need it anyways later for other tests

2018-09-11 14:25 UTC, josojo approved these changes
Like it a lot.

2018-09-11 14:25 UTC, josojo commented on test/merkle.js
> +    fastForward,
Do you need this one? What is the proof ForDepositBlock for?

2018-09-11 14:46 UTC, fleupold reviewed
Looks good now. Just a few minor suggestions. I'd like to see the rename happening before accepting.

2018-09-11 14:46 UTC, fleupold commented on test/merkle.js
>      merkle = await MerkleMock.new();
I'd prefer doing this in each test case, to avoid state being stored between test cases. It's not really important here since we are not storing any state, but I'd prefer to use this pattern generally.

2018-09-11 14:46 UTC, fleupold commented on test/merkle.js
> +describe('Height 4: check left and right most txn', function () {
Is this test adding any value, given that you have already tested height 2? If at all should we check height 16 or does this take too long?

2018-09-11 14:46 UTC, fleupold commented on test/utilities.js
> +const assertRejects = async (q, msg) => {
I'm surprised this code isn't super common. Can we maybe import this from somewhere instead of copying the code in our repo?

2018-09-11 14:46 UTC, fleupold commented on test/merkle.js
> +    fastForward,
Same with catchError, zeroHashes

2018-09-11 14:56 UTC, bh2smith commented on test/merkle.js
> +      var proof = '0xc89efdaa54c0f20c7adf612882df0950f5a951637e0307cdcb4c672f298b8bc627c2feed9df4c4903bfc9f1bda886662bebc8ba175ccdb3d1da20ce3a32441ba519d76fbbd63a3ac72cdfee0c0e650d76e933ef34227d72ef2
All done with the JS-tests! That was fun!

2018-09-11 17:15 UTC, fleupold approved these changes
Looks great!

It would be awesome if you could address the remaining comments before merging.

2018-09-11 17:15 UTC, fleupold commented on test/plasma.js
> +contract('Plasma', (accounts) => {
nit: these changes are not related to this pull request.

2018-09-11 17:15 UTC, fleupold commented on test/merkle.js
> +    merkle = await MerkleWrapper.new();
as per previous comment, I'd prefer if we create a new object under test inside each test to avoid dependencies on the order of execution.

2018-09-11 17:42 UTC, bh2smith commented on test/merkle.js
> +    fastForward,
I was not aware I could "choose" not to import things I don't need from the utilities file. These are leftovers from cut contract (I believe). Not only shall I remove the import statements, but will get rid of any functions that are not needed anywhere in the next commit.

2018-09-11 17:56 UTC, bh2smith commented on test/merkle.js
> +describe('Height 4: check left and right most txn', function () {
I would say that it doesn't really add any value as the height 2 tree is non-trivial anyway. However, while experimenting with this, I did notice that our checkMembership function is not  equip to handle any lop-sided trees (i.e. those without an exact power of 2 number of leaves) that are not implemented with 'padded' zeros. Will remove this until further notice.

2018-09-11 17:57 UTC, bh2smith commented on test/utilities.js
> +const assertRejects = async (q, msg) => {
I will take a look into it and really hope to find something.

2018-09-11 17:58 UTC, bh2smith commented on test/plasma.js
> +contract('Plasma', (accounts) => {
They aren't, but I didn't want to make a whole new one just for this.

2018-09-11 17:59 UTC, bh2smith commented on test/merkle.js
> +    merkle = await MerkleWrapper.new();
Ahhh, Yes. Of course.

2018-09-11 18:10 UTC, bh2smith commented on test/merkle.js
> +    merkle = await MerkleWrapper.new();
Although, I have removed the second section of tests for this contract. In this case it simply boils down to moving the before-async stuff into the one block of tests. 

PS - I wasn't able to take the await out of the async because of some js-error that I am too young to understand.

```
SyntaxError: await is only valid in async function
```

2018-09-11 18:19 UTC, bh2smith commented on test/utilities.js
> +const assertRejects = async (q, msg) => {
I looked around briefly and will continue to look, but I think I will add a "good first issue" to investigate this.

2018-09-11 18:37 UTC, fleupold commented on test/plasma.js
> +contract('Plasma', (accounts) => {
I understand. Usually it's nice to keep changes isolated in case we have to revert certain pull requests (then we really only revert what the pull request was about).
Doing small cleanups like this are likely going to be immediately accepted and merged so it's really just the overhead of creating another pr. I wonder if we can make our git workflow more efficient to encourage that.

I usually `git stash` changes like that on the unrelated branch and once I'm done with the current PR, I rebase back on master, un-stash them and create a new branch/commit with them.

2018-09-11 18:44 UTC, merged