[UnitTests] ChallengeTransactionExitWithTransaction
gnosis/dex-plasma pull request #36
Opened 2018-09-27 15:32 UTC by fleupold

2018-09-27 19:02 UTC, josojo approved these changes
Can be merged once the failing test passes.

Maybe you want to change the code and do a whole deletion of the exits structs, check out the comments

2018-09-27 19:02 UTC, josojo commented on test/plasma.js
> +      owner = (await plasma.getExit.call(utxoPosition))[0]
As you mentioned in slack: It would have been great to test here that also this exit does not withdraw/burn any funds in the finalize function.

Maybe you want to change this line and delete the whole struct

        // Delete the owner but keep the amount to prevent another exit.
        delete exits[eUtxoPos].owner;
I think they kept it, in order to prevent the same exit request again. But actually, bonding should do the disincentivation and not storing data on the blockchain.

2018-09-27 20:32 UTC, bh2smith requested changes
All is fine here, but still have the same issue with the finalizeExit test that didn't run on the branch that this is based. Also we should remove the dot only.

Once again, I would recommend having these branches caught up with develop to see how they play. I am not sure how the first branch got passed travis, but the failed test came from Fast Forward. The only other problem with this branch is the linter on import dot sol which could easily be resolved by rebasing on develop.

2018-09-27 20:32 UTC, bh2smith commented on test/plasma.js
> +  describe.only("challengeTransactionExitWithTransaction", () => {
dot only should be removed.

2018-09-27 20:32 UTC, bh2smith commented on test/plasma.js
> +      owner = (await plasma.getExit.call(utxoPosition))[0]
This is kinda weird. I see in the comment that they are trying to prevent something but shouldn't there be a better way. Can we put this in some sort of re-evaluation checklist for later? I assume the point is to get the error "Exit already exists for this utxo". If we are to adjust this, then we may also have to reconsider the 3 require statement in _addExitToQueue_

2018-09-28 08:54 UTC, fleupold commented on test/plasma.js
> +      owner = (await plasma.getExit.call(utxoPosition))[0]
I think it's fair to assert that you can only exit once. If I were to design this in a regular programming language. I would have a flag on the exit that says "challenged" or "processed" instead of implicitly encoding this information in the absence of an owner address. However, I assume this is less gas efficient.

I changed the code and added a test case that makes sure we are not burning any tokens. Check out the latest commit.

2018-09-30 22:41 UTC, bh2smith approved these changes

2018-09-30 22:45 UTC, bh2smith approved these changes
This is fine, but I am getting exceeds gas limit errors again!

2018-09-30 23:04 UTC, merged