[WIP] Test validate
gnosis/dex-plasma pull request #37
Opened 2018-09-27 20:52 UTC by bh2smith

These tests should cover all possible outcomes but still only getting 87.5% on the branch coverage. Not sure whats up but would like to get to the bottom of this. Wanted to avoid putting too many todos around the code, but I really think we should pass **inputCount** as a **Boolean** especially considering it is only able to hand the case for two inputs anyway. 

This will involve/require that we also change the uses of this function in the plasma contract. Not a huge refactoring, and could be done easily.

2018-09-28 08:17 UTC, josojo commented
Yeah, I really don't know whether it is best to work with many outputs or just two. 
Sure, if we use more than 2, transactions get longer and everything uses more gas. But on the other hand side, we could later merge much better different outputs with just one transaction instead of many dependent transactions.

Hm... my gut feeling is that working with 2 outputs would be better...

2018-09-28 08:17 UTC, josojo approved these changes

2018-09-28 09:18 UTC, fleupold requested changes
Can we use the same sha3 implementation we use for the plasma and merkle contract tests as well?

Is it possible to run a coverage analysis to identify which branches are not covered?

2018-09-28 09:18 UTC, fleupold commented on test/utilities.js
> +function keccak256(...args) {
I believe this is equivalent to what the already imported sha3 function is doing. Can we try using this one instead?

2018-09-28 09:18 UTC, fleupold commented on test/validate.js
> +    it("Basic Pass & Fail - Single Input", async () => {
I tend to prefer test cases testing one thing, e.g. here `it("accepts valid signature with one input")` and `it("rejects invalid signature with one input")`, etc.

2018-09-30 21:39 UTC, bh2smith commented on test/utilities.js
> +function keccak256(...args) {
I tried using this one and they differ. This non-standard JS library thing is bullshit.

2018-09-30 21:41 UTC, bh2smith commented on test/utilities.js
> +function keccak256(...args) {
```
toHex(sha3([txHash, rootHash])) = 0x54a8c...
keccak256(txHash, rootHash) = 0xbd6aa...
```

2018-09-30 21:44 UTC, bh2smith commented on test/utilities.js
> +function keccak256(...args) {
I will, thus, change all occurrences of *web3.sha3* to *toHex(sha3)* but will leave keccak for items that need to be hashed together unless you have a better suggestion.

2018-09-30 22:39 UTC, bh2smith commented
@fleupold  - ready to be checked again!

2018-10-01 08:31 UTC, fleupold commented
I have submitted a suggestion on how it would work without the `keccak256`. In general I'm not against convenience functions, but this one we obviously copied from some stackoverflow answer and in it should do exactly what the `ethereumjs-util` `sha3` does.

Feel free to revert my changes, but in that case please replace all use of `ethereumjs-util` `sha3` with the new `keccak256`

2018-10-01 08:31 UTC, fleupold approved these changes

2018-10-02 02:13 UTC, merged